plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
    id "me.modmuss50.mod-publish-plugin" version "2.1.1"
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven {
        name = "ModMaven (MI, GrandPower, JEI)"
        url = "https://modmaven.dev"
        content {
            includeGroup "aztech" // MI
            includeGroup "dev.technici4n" // GrandPower
            includeGroup "mezz.jei" // JEI
        }
    }
    maven {
        name 'GTCEu Maven (ModularUI)'
        url 'https://maven.gtceu.com'
    }
    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
        content {
            includeGroup("curse.maven")
        }
    }
    maven {
        name = "TerraformersMC (EMI)"
        url = "https://maven.terraformersmc.com/releases/"
        content {
            includeGroup "dev.emi"
        }
    }
    maven {
        name = "Shedaniel (REI)"
        url = "https://maven.shedaniel.me"
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    setAccessTransformers {
        file("src/main/resources/${project.mod_id}-accesstransformer.cfg")
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    compileOnly "org.projectlombok:lombok:1.18.30"
    annotationProcessor "org.projectlombok:lombok:1.18.30"

    implementation "dev.technici4n:GrandPower:${grandpower_version}"
    implementation "aztech:Modern-Industrialization:${modern_industrialization_version}"
    implementation "org.appliedenergistics:guideme:${project.guideme_version}"

    jarJar(implementation("brachy.modularui:modularui-mc1.21.1:${modularui_version}")) {
        version {
            prefer "${modularui_version}"
        }
    }

    compileOnly "dev.emi:emi-neoforge:${emi_version}:api"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}"
    switch("${active_item_viewer}") {
        case "emi":
            runtimeOnly "dev.emi:emi-neoforge:${emi_version}"
            break
        case "jei":
            runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
            break
        case "rei":
            runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
            break
        default:
            break
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             modern_industrialization_version_range : modern_industrialization_version_range,
                             modularui_version_range : modularui_version_range,
                             guideme_version_range : guideme_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

ext.getChangeLog = { ->
    return "Initial alpha release"
}

publishMods {
    file = jar.archiveFile
    version = "${project.mod_version}"
    displayName = "${project.mod_version}"
    modLoaders.add("neoforge")
    type = ALPHA //STABLE
    changelog = project.getChangeLog()

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = "1625971"
        projectSlug = "amimi"
        minecraftVersions.add("${project.minecraft_version}")
        client = true
        server = true

        embeds("modularui")
        requires("modern-industrialization")
        requires("emi")
//        optional("emi")
//        optional("jei")

        announcementTitle = "Download from CurseForge"
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "hUqkjVpm"
        minecraftVersions.add("${project.minecraft_version}")
        environment = CLIENT_AND_SERVER

//      embeds("modularui")
        requires("modern-industrialization")
        requires("emi")
//        optional("emi")
//        optional("jei")

        announcementTitle = "Download from Modrinth"
    }

//    discord {
//        webhookUrl = providers.environmentVariable("CAFETERIA_MOD_RELEASE_WEBHOOK")
//        username = "${rootProject.mod_name}"
//        avatarUrl = "https://cdn.modrinth.com/data/jXqDKaST/c0bd6980760c14410cc9a517ec5176d230f817d1_96.webp"
//
//        content = changelog.map { "# " + (rootProject.mod_name as String) + " " + (project.mod_version as String) + " has been released \n" + it}
//    }
}