org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.234
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
## Mod Properties
mod_id=amimi
mod_name=AMIMI (Advanced Multiblock Info for Modern Industrialization)
mod_license=GNU LGPL 3.0
mod_version=0.0.1-ALPHA+1.21.1
mod_group_id=me.luligabi
mod_authors=Luligabi1
mod_description=Improves on Modern Industrialization's Multiblock Information tab by adding a 3D preview of the multiblock directly onto your recipe viewer of choice
## Dependencies
grandpower_version=3.0.0
modern_industrialization_version=2.5.6
guideme_version=21.1.9
modularui_version=3.3.1-SNAPSHOT
emi_version=1.1.24+1.21.1
jei_version=19.25.1.328
rei_version=16.0.799
## Ranges
modern_industrialization_version_range=[2.5.6, 2.6-)
modularui_version_range=[3.3.1-SNAPSHOT,)
guideme_version_range=[21.1.9, 21.2-)
## Misc
active_item_viewer=emi
